/*
  SD.Next ModernUI — generated by @vladmandic/build
*/


// src/vendor/split.js
var Split = (function(global, factory) {
  if (typeof define === "function" && define.amd) {
    return define(factory);
  } else {
    const result = factory();
    global.Split = result;
    return result;
  }
})(typeof globalThis !== "undefined" ? globalThis : void 0, (() => {
  const global = typeof window !== "undefined" ? window : null;
  const ssr = global === null;
  const document2 = !ssr ? global.document : void 0;
  const addEventListener = "addEventListener";
  const removeEventListener = "removeEventListener";
  const getBoundingClientRect = "getBoundingClientRect";
  const gutterStartDragging = "_a";
  const aGutterSize = "_b";
  const bGutterSize = "_c";
  const HORIZONTAL = "horizontal";
  const NOOP = function() {
    return false;
  };
  const calc = ssr ? "calc" : `${["", "-webkit-", "-moz-", "-o-"].filter((prefix) => {
    const el = document2.createElement("div");
    el.style.cssText = `width:${prefix}calc(9px)`;
    return !!el.style.length;
  }).shift()}calc`;
  const isString = function(v) {
    return typeof v === "string" || v instanceof String;
  };
  const elementOrSelector = function(el) {
    if (isString(el)) {
      const ele = document2.querySelector(el);
      if (!ele) {
        throw new Error(`Selector ${el} did not match a DOM element`);
      }
      return ele;
    }
    return el;
  };
  const getOption = function(options, propName, def) {
    const value = options[propName];
    if (value !== void 0) {
      return value;
    }
    return def;
  };
  const getGutterSize = function(gutterSize, isFirst, isLast, gutterAlign) {
    if (isFirst) {
      if (gutterAlign === "end") {
        return 0;
      }
      if (gutterAlign === "center") {
        return gutterSize / 2;
      }
    } else if (isLast) {
      if (gutterAlign === "start") {
        return 0;
      }
      if (gutterAlign === "center") {
        return gutterSize / 2;
      }
    }
    return gutterSize;
  };
  const defaultGutterFn = function(i, gutterDirection) {
    const gut = document2.createElement("div");
    gut.className = `gutter gutter-${gutterDirection}`;
    return gut;
  };
  const defaultElementStyleFn = function(dim, size, gutSize) {
    const style = {};
    if (!isString(size)) {
      style[dim] = `${calc}(${size}% - ${gutSize}px)`;
    } else {
      style[dim] = size;
    }
    return style;
  };
  const defaultGutterStyleFn = function(dim, gutSize) {
    let obj;
    return obj = {}, obj[dim] = `${gutSize}px`, obj;
  };
  const Split2 = function(idsOption, options) {
    if (options === void 0) options = {};
    if (ssr) {
      return {};
    }
    let ids = idsOption;
    let dimension;
    let clientAxis;
    let position;
    let positionEnd;
    let clientSize;
    let elements;
    if (Array.from) {
      ids = Array.from(ids);
    }
    const firstElement = elementOrSelector(ids[0]);
    const parent = firstElement.parentNode;
    const parentStyle = getComputedStyle ? getComputedStyle(parent) : null;
    const parentFlexDirection = parentStyle ? parentStyle.flexDirection : null;
    let sizes = getOption(options, "sizes") || ids.map(() => 100 / ids.length);
    const minSize = getOption(options, "minSize", 100);
    const minSizes = Array.isArray(minSize) ? minSize : ids.map(() => minSize);
    const maxSize = getOption(options, "maxSize", Infinity);
    const maxSizes = Array.isArray(maxSize) ? maxSize : ids.map(() => maxSize);
    const expandToMin = getOption(options, "expandToMin", false);
    const gutterSize = getOption(options, "gutterSize", 10);
    const gutterAlign = getOption(options, "gutterAlign", "center");
    const snapOffset = getOption(options, "snapOffset", 30);
    const snapOffsets = Array.isArray(snapOffset) ? snapOffset : ids.map(() => snapOffset);
    const dragInterval = getOption(options, "dragInterval", 1);
    const direction = getOption(options, "direction", HORIZONTAL);
    const cursor = getOption(
      options,
      "cursor",
      direction === HORIZONTAL ? "col-resize" : "row-resize"
    );
    const gutter = getOption(options, "gutter", defaultGutterFn);
    const elementStyle = getOption(
      options,
      "elementStyle",
      defaultElementStyleFn
    );
    const gutterStyle = getOption(options, "gutterStyle", defaultGutterStyleFn);
    if (direction === HORIZONTAL) {
      dimension = "width";
      clientAxis = "clientX";
      position = "left";
      positionEnd = "right";
      clientSize = "clientWidth";
    } else if (direction === "vertical") {
      dimension = "height";
      clientAxis = "clientY";
      position = "top";
      positionEnd = "bottom";
      clientSize = "clientHeight";
    }
    function setElementSize(el, size, gutSize, i) {
      const style = elementStyle(dimension, size, gutSize, i);
      Object.keys(style).forEach((prop) => {
        el.style[prop] = style[prop];
      });
    }
    function setGutterSize(gutterElement, gutSize, i) {
      const style = gutterStyle(dimension, gutSize, i);
      Object.keys(style).forEach((prop) => {
        gutterElement.style[prop] = style[prop];
      });
    }
    function getSizes() {
      return elements.map((element) => element.size);
    }
    function getMousePosition(e) {
      if ("touches" in e) {
        return e.touches[0][clientAxis];
      }
      return e[clientAxis];
    }
    function adjust(offset) {
      const a = elements[this.a];
      const b = elements[this.b];
      const percentage = a.size + b.size;
      a.size = offset / this.size * percentage;
      b.size = percentage - offset / this.size * percentage;
      setElementSize(a.element, a.size, this[aGutterSize], a.i);
      setElementSize(b.element, b.size, this[bGutterSize], b.i);
    }
    function drag(e) {
      let offset;
      const a = elements[this.a];
      const b = elements[this.b];
      if (!this.dragging) {
        return;
      }
      offset = getMousePosition(e) - this.start + (this[aGutterSize] - this.dragOffset);
      if (dragInterval > 1) {
        offset = Math.round(offset / dragInterval) * dragInterval;
      }
      if (offset <= a.minSize + a.snapOffset + this[aGutterSize]) {
        offset = a.minSize + this[aGutterSize];
      } else if (offset >= this.size - (b.minSize + b.snapOffset + this[bGutterSize])) {
        offset = this.size - (b.minSize + this[bGutterSize]);
      }
      if (offset >= a.maxSize - a.snapOffset + this[aGutterSize]) {
        offset = a.maxSize + this[aGutterSize];
      } else if (offset <= this.size - (b.maxSize - b.snapOffset + this[bGutterSize])) {
        offset = this.size - (b.maxSize + this[bGutterSize]);
      }
      adjust.call(this, offset);
      getOption(options, "onDrag", NOOP)(getSizes());
    }
    function calculateSizes() {
      const a = elements[this.a].element;
      const b = elements[this.b].element;
      const aBounds = a[getBoundingClientRect]();
      const bBounds = b[getBoundingClientRect]();
      this.size = aBounds[dimension] + bBounds[dimension] + this[aGutterSize] + this[bGutterSize];
      this.start = aBounds[position];
      this.end = aBounds[positionEnd];
    }
    function innerSize(element) {
      if (!getComputedStyle) {
        return null;
      }
      const computedStyle = getComputedStyle(element);
      if (!computedStyle) {
        return null;
      }
      let size = element[clientSize];
      if (size === 0) {
        return null;
      }
      if (direction === HORIZONTAL) {
        size -= parseFloat(computedStyle.paddingLeft) + parseFloat(computedStyle.paddingRight);
      } else {
        size -= parseFloat(computedStyle.paddingTop) + parseFloat(computedStyle.paddingBottom);
      }
      return size;
    }
    function trimToMin(sizesToTrim) {
      const parentSize = innerSize(parent);
      if (parentSize === null) {
        return sizesToTrim;
      }
      if (minSizes.reduce((a, b) => a + b, 0) > parentSize) {
        return sizesToTrim;
      }
      let excessPixels = 0;
      const toSpare = [];
      const pixelSizes = sizesToTrim.map((size, i) => {
        const pixelSize = parentSize * size / 100;
        const elementGutterSize = getGutterSize(
          gutterSize,
          i === 0,
          i === sizesToTrim.length - 1,
          gutterAlign
        );
        const elementMinSize = minSizes[i] + elementGutterSize;
        if (pixelSize < elementMinSize) {
          excessPixels += elementMinSize - pixelSize;
          toSpare.push(0);
          return elementMinSize;
        }
        toSpare.push(pixelSize - elementMinSize);
        return pixelSize;
      });
      if (excessPixels === 0) {
        return sizesToTrim;
      }
      return pixelSizes.map((pixelSize, i) => {
        let newPixelSize = pixelSize;
        if (excessPixels > 0 && toSpare[i] - excessPixels > 0) {
          const takenPixels = Math.min(
            excessPixels,
            toSpare[i] - excessPixels
          );
          excessPixels -= takenPixels;
          newPixelSize = pixelSize - takenPixels;
        }
        return newPixelSize / parentSize * 100;
      });
    }
    function stopDragging() {
      const self = this;
      const a = elements[self.a].element;
      const b = elements[self.b].element;
      if (self.dragging) {
        getOption(options, "onDragEnd", NOOP)(getSizes());
      }
      self.dragging = false;
      global[removeEventListener]("mouseup", self.stop);
      global[removeEventListener]("touchend", self.stop);
      global[removeEventListener]("touchcancel", self.stop);
      global[removeEventListener]("mousemove", self.move);
      global[removeEventListener]("touchmove", self.move);
      self.stop = null;
      self.move = null;
      a[removeEventListener]("selectstart", NOOP);
      a[removeEventListener]("dragstart", NOOP);
      b[removeEventListener]("selectstart", NOOP);
      b[removeEventListener]("dragstart", NOOP);
      a.style.userSelect = "";
      a.style.webkitUserSelect = "";
      a.style.MozUserSelect = "";
      a.style.pointerEvents = "";
      b.style.userSelect = "";
      b.style.webkitUserSelect = "";
      b.style.MozUserSelect = "";
      b.style.pointerEvents = "";
      self.gutter.style.cursor = "";
      self.parent.style.cursor = "";
      document2.body.style.cursor = "";
    }
    function startDragging(e) {
      if ("button" in e && e.button !== 0) {
        return;
      }
      const self = this;
      const a = elements[self.a].element;
      const b = elements[self.b].element;
      if (!self.dragging) {
        getOption(options, "onDragStart", NOOP)(getSizes());
      }
      if (e.type !== "touchstart") {
        e.preventDefault();
      }
      self.dragging = true;
      self.move = drag.bind(self);
      self.stop = stopDragging.bind(self);
      global[addEventListener]("mouseup", self.stop);
      global[addEventListener]("touchend", self.stop);
      global[addEventListener]("touchcancel", self.stop);
      global[addEventListener]("mousemove", self.move);
      global[addEventListener]("touchmove", self.move);
      a[addEventListener]("selectstart", NOOP);
      a[addEventListener]("dragstart", NOOP);
      b[addEventListener]("selectstart", NOOP);
      b[addEventListener]("dragstart", NOOP);
      a.style.userSelect = "none";
      a.style.webkitUserSelect = "none";
      a.style.MozUserSelect = "none";
      a.style.pointerEvents = "none";
      b.style.userSelect = "none";
      b.style.webkitUserSelect = "none";
      b.style.MozUserSelect = "none";
      b.style.pointerEvents = "none";
      self.gutter.style.cursor = cursor;
      self.parent.style.cursor = cursor;
      document2.body.style.cursor = cursor;
      calculateSizes.call(self);
      self.dragOffset = getMousePosition(e) - self.end;
    }
    sizes = trimToMin(sizes);
    const pairs = [];
    elements = ids.map((id, i) => {
      const element = {
        element: elementOrSelector(id),
        size: sizes[i],
        minSize: minSizes[i],
        maxSize: maxSizes[i],
        snapOffset: snapOffsets[i],
        i
      };
      let pair;
      if (i > 0) {
        pair = {
          a: i - 1,
          b: i,
          dragging: false,
          direction,
          parent
        };
        pair[aGutterSize] = getGutterSize(
          gutterSize,
          i - 1 === 0,
          false,
          gutterAlign
        );
        pair[bGutterSize] = getGutterSize(
          gutterSize,
          false,
          i === ids.length - 1,
          gutterAlign
        );
        if (parentFlexDirection === "row-reverse" || parentFlexDirection === "column-reverse") {
          const temp = pair.a;
          pair.a = pair.b;
          pair.b = temp;
        }
      }
      if (i > 0) {
        const gutterElement = gutter(i, direction, element.element);
        setGutterSize(gutterElement, gutterSize, i);
        pair[gutterStartDragging] = startDragging.bind(pair);
        gutterElement[addEventListener](
          "mousedown",
          pair[gutterStartDragging]
        );
        gutterElement[addEventListener](
          "touchstart",
          pair[gutterStartDragging],
          { passive: true }
        );
        parent.insertBefore(gutterElement, element.element);
        pair.gutter = gutterElement;
      }
      setElementSize(
        element.element,
        element.size,
        getGutterSize(
          gutterSize,
          i === 0,
          i === ids.length - 1,
          gutterAlign
        ),
        i
      );
      if (i > 0) {
        pairs.push(pair);
      }
      return element;
    });
    function adjustToMin(element) {
      const isLast = element.i === pairs.length;
      const pair = isLast ? pairs[element.i - 1] : pairs[element.i];
      calculateSizes.call(pair);
      const size = isLast ? pair.size - element.minSize - pair[bGutterSize] : element.minSize + pair[aGutterSize];
      adjust.call(pair, size);
    }
    elements.forEach((element) => {
      const computedSize = element.element[getBoundingClientRect]()[dimension];
      if (computedSize < element.minSize) {
        if (expandToMin) {
          adjustToMin(element);
        } else {
          element.minSize = computedSize;
        }
      }
    });
    function setSizes(newSizes) {
      const trimmed = trimToMin(newSizes);
      trimmed.forEach((newSize, i) => {
        if (i > 0) {
          const pair = pairs[i - 1];
          const a = elements[pair.a];
          const b = elements[pair.b];
          a.size = trimmed[i - 1];
          b.size = newSize;
          setElementSize(a.element, a.size, pair[aGutterSize], a.i);
          setElementSize(b.element, b.size, pair[bGutterSize], b.i);
        }
      });
    }
    function destroy(preserveStyles, preserveGutter) {
      pairs.forEach((pair) => {
        if (preserveGutter !== true) {
          pair.parent.removeChild(pair.gutter);
        } else {
          pair.gutter[removeEventListener](
            "mousedown",
            pair[gutterStartDragging]
          );
          pair.gutter[removeEventListener](
            "touchstart",
            pair[gutterStartDragging]
          );
        }
        if (preserveStyles !== true) {
          const style = elementStyle(
            dimension,
            pair.a.size,
            pair[aGutterSize]
          );
          Object.keys(style).forEach((prop) => {
            elements[pair.a].element.style[prop] = "";
            elements[pair.b].element.style[prop] = "";
          });
        }
      });
    }
    return {
      setSizes,
      getSizes,
      collapse: function collapse(i) {
        adjustToMin(elements[i]);
      },
      destroy,
      parent,
      pairs
    };
  };
  return Split2;
}));
var split_default = Split;

// src/state.ts
var state = {
  appUiUx: null,
  uiFlagInitialized: false,
  uiFlagPortalInitialized: false,
  portalTotal: 0,
  asideFocusTracker: 0
};

// src/utils.ts
var setStored = (key, val) => {
  if (!window.opts.uiux_persist_layout) return;
  try {
    localStorage.setItem(`ui-${key}`, JSON.stringify(val));
  } catch {
  }
};
var getStored = (key) => {
  if (!window.opts.uiux_persist_layout) return void 0;
  let val;
  try {
    val = JSON.parse(localStorage.getItem(`ui-${key}`) ?? "null");
  } catch {
  }
  return val;
};
function functionWaitForFlag(checkFlag) {
  return async () => new Promise((resolve) => {
    const check = () => checkFlag() ? resolve() : setTimeout(check, 50);
    check();
  });
}

// src/components.ts
var splitInstances = {};
function initSplitComponents() {
  const appUiUx = state.appUiUx;
  if (!appUiUx) return;
  appUiUx.querySelectorAll("div.split").forEach((elem) => {
    const id = elem.id;
    const nid = appUiUx.querySelector(`#${id}`);
    const direction = nid?.getAttribute("direction") === "vertical" ? "vertical" : "horizontal";
    const gutterSize = nid?.getAttribute("gutterSize") || "8";
    const ids = [];
    const initSizes = [];
    const minSizes = [];
    const maxSizes = [];
    const containers = appUiUx.querySelectorAll(`#${id} > div.split-container`);
    containers.forEach((c, index) => {
      const initSize = c.getAttribute("data-initSize");
      const minSize = c.getAttribute("data-minSize");
      const maxSize = c.getAttribute("data-maxSize");
      ids.push(`#${c.id}`);
      try {
        const storedSize = getStored(`${id}-sizes`);
        if (storedSize && Array.isArray(storedSize) && storedSize.every((n) => typeof n === "number") && storedSize.length === containers.length) {
          initSizes.push(storedSize[index]);
        } else {
          initSizes.push(initSize ? parseInt(initSize) : 100 / containers.length);
        }
      } catch {
        initSizes.push(initSize ? parseInt(initSize) : 100 / containers.length);
      }
      minSizes.push(minSize ? parseInt(minSize) : 0);
      maxSizes.push(maxSize ? parseInt(maxSize) : Infinity);
    });
    const onDragEnd = (evt) => setStored(`${id}-sizes`, evt);
    splitInstances[id] = split_default(ids, {
      sizes: initSizes,
      minSize: minSizes,
      maxSize: maxSizes,
      direction,
      gutterSize: parseInt(gutterSize),
      snapOffset: 0,
      dragInterval: 1,
      onDragEnd,
      elementStyle(_dimension, size, gs) {
        return {
          "flex-basis": `calc(${size}% - ${gs}px)`
        };
      },
      gutterStyle(_dimension, gs) {
        return {
          "flex-basis": `${gs}px`,
          "min-width": `${gs}px`,
          "min-height": `${gs}px`
        };
      }
    });
  });
}
function restoreAccordionState() {
  const appUiUx = state.appUiUx;
  if (!appUiUx) return;
  appUiUx.querySelectorAll(".accordion-bar").forEach((elem) => {
    const acc = elem.parentElement;
    const accSplit = acc?.closest(".split-container");
    const accTrigger = acc ? appUiUx.querySelector(acc.getAttribute("iconTrigger") ?? "") : null;
    if (acc && accSplit && acc.className.indexOf("accordion-vertical") !== -1 && accSplit.className.indexOf("split") !== -1) {
      const savedClasses = getStored(`ui-${acc.id}-class`);
      if (savedClasses && !savedClasses.includes("expand")) accTrigger?.click();
    }
  });
}
function initAccordionComponents() {
  const appUiUx = state.appUiUx;
  if (!appUiUx) return;
  appUiUx.querySelectorAll(".accordion-bar").forEach((elem) => {
    const acc = elem.parentElement;
    if (!acc) return;
    const accSplit = acc.closest(".split-container");
    const accTrigger = appUiUx.querySelector(acc.getAttribute("iconTrigger") ?? "");
    if (accTrigger) elem.classList.add("pointer-events-none");
    if (accSplit && acc.className.indexOf("accordion-vertical") !== -1 && accSplit.className.indexOf("split") !== -1) {
      acc.classList.add("expand");
      const splitInstance = splitInstances[accSplit.parentElement?.id ?? ""];
      accSplit.setAttribute("data-sizes", JSON.stringify(splitInstance.getSizes()));
      accTrigger?.addEventListener("click", () => {
        acc.classList.toggle("expand");
        setStored(`ui-${acc.id}-class`, acc.className);
        if (accSplit.className.indexOf("v-expand") !== -1) {
          accSplit.classList.remove("v-expand");
          accSplit.style.removeProperty("min-width");
          splitInstance.setSizes(JSON.parse(accSplit.getAttribute("data-sizes") ?? "[]"));
        } else {
          accSplit.classList.add("v-expand");
          const sizes = splitInstance.getSizes();
          accSplit.setAttribute("data-sizes", JSON.stringify(sizes));
          if (acc.className.indexOf("left") !== -1) {
            sizes[sizes.length - 1] = 100;
            sizes[sizes.length - 2] = 0;
          } else {
            sizes[sizes.length - 1] = 0;
            sizes[sizes.length - 2] = 100;
          }
          const padding = parseFloat(window.getComputedStyle(elem, null).getPropertyValue("padding-left")) * 2;
          accSplit.style.minWidth = `${elem.offsetWidth + padding}px`;
          splitInstance.setSizes(sizes);
        }
      });
    } else {
      accTrigger?.addEventListener("click", () => {
        acc.classList.toggle("expand");
        setStored(`ui-${acc.id}-class`, acc.className);
      });
    }
    const fullTrigger = acc.getAttribute("iconFullTrigger");
    if (fullTrigger) {
      appUiUx.querySelector(fullTrigger)?.addEventListener("click", () => {
        acc.classList.toggle("full-expand");
        setStored(`ui-${acc.id}-class`, acc.className);
      });
    }
  });
}
function initTabComponents() {
  function hideActive(tab) {
    const appUiUx2 = state.appUiUx;
    if (!appUiUx2) return;
    tab.classList.remove("active");
    const tabItemId = tab.getAttribute("tabItemId");
    if (tabItemId) {
      appUiUx2.querySelectorAll(tabItemId).forEach((tabItem) => {
        tabItem.classList.remove("fade-in");
        tabItem.classList.add("fade-out");
      });
    }
  }
  function showActive(tab) {
    const appUiUx2 = state.appUiUx;
    if (!appUiUx2) return;
    tab.classList.add("active");
    const tabItemId = tab.getAttribute("tabItemId");
    if (tabItemId) {
      appUiUx2.querySelectorAll(tabItemId).forEach((tabItem) => {
        tabItem.classList.add("fade-in");
        tabItem.classList.remove("fade-out");
      });
    }
  }
  function triggerAccordion(elem, wasActive, checkStored) {
    const appUiUx2 = state.appUiUx;
    const accBar = elem.closest(".accordion-bar");
    if (!accBar || !appUiUx2) return;
    const acc = accBar.parentElement;
    if (!acc) return;
    const accTriggerSelector = acc.getAttribute("iconTrigger");
    const accFullTriggerSelector = acc.getAttribute("iconFullTrigger");
    const accTrigger = accTriggerSelector ? appUiUx2.querySelector(accTriggerSelector) : null;
    const accFullTrigger = accFullTriggerSelector ? appUiUx2.querySelector(accFullTriggerSelector) : null;
    const accStoredClasses = getStored(`ui-${acc.id}-class`) || "";
    const storedAsCollapsed = accStoredClasses && accStoredClasses.indexOf("expand") === -1;
    const storedAsFullExpanded = accStoredClasses && accStoredClasses.indexOf("full-expand") !== -1;
    const shouldExpand = !acc.classList.contains("expand");
    const shouldCollapse = acc.classList.contains("expand") && !acc.classList.contains("full-expand") && (wasActive || checkStored && storedAsCollapsed);
    const shouldFullExpand = acc.classList.contains("expand") && !acc.classList.contains("full-expand") && (checkStored && storedAsFullExpanded);
    if (shouldExpand || shouldCollapse) {
      if (accTrigger) accTrigger.click();
      else accBar.click();
    }
    if (shouldFullExpand) {
      if (accFullTrigger) accFullTrigger.click();
    }
  }
  const appUiUx = state.appUiUx;
  if (!appUiUx) return;
  appUiUx.querySelectorAll(".xtabs-tab").forEach((elem) => {
    const tabGroup = elem.getAttribute("tabGroup");
    const tabParent = elem.parentElement;
    const uid = tabGroup || tabParent?.id;
    const siblingTabs = [...tabGroup ? appUiUx.querySelectorAll(`[tabGroup="${tabGroup}"]`) : tabParent ? tabParent.children : []].filter((tab) => tab !== elem);
    elem.addEventListener("click", () => {
      if (uid) setStored(`tab-${uid}-current`, elem.id);
      siblingTabs.filter((tab) => tab.classList.contains("active")).forEach(hideActive);
      const wasActive = elem.classList.contains("active");
      showActive(elem);
      triggerAccordion(elem, wasActive, false);
    });
    const storedTab = uid ? getStored(`tab-${uid}-current`) || "" : "";
    const active = storedTab ? storedTab === elem.id : elem.getAttribute("active");
    if (active) {
      showActive(elem);
      triggerAccordion(elem, false, true);
    } else {
      hideActive(elem);
    }
  });
  function showHideAnchors(anchor, index) {
    Array.from(anchor.children).forEach((elem) => {
      if (elem.matches(`[anchor*="${index}"]`)) elem.style.display = "flex";
      else elem.style.display = "none";
    });
  }
  appUiUx.querySelectorAll(".xtabs-anchor").forEach((anchor) => {
    const tabNav = document.querySelector(anchor.getAttribute("anchorNav") ?? "");
    if (tabNav) {
      const observer = new MutationObserver(() => {
        const index = Array.from(tabNav.children).findIndex((btn) => btn.classList.contains("selected")) + 1;
        showHideAnchors(anchor, index);
      });
      observer.observe(tabNav, { attributes: true, attributeFilter: ["class"], childList: true });
    }
    showHideAnchors(anchor, 1);
  });
}
function initButtonComponents() {
  const appUiUx = state.appUiUx;
  if (!appUiUx) return;
  appUiUx.querySelectorAll(".sd-button").forEach((elem) => {
    const toggle = elem.getAttribute("toggle");
    const active = elem.getAttribute("active");
    const input = elem.querySelector("input");
    if (input) {
      if (input.checked === true && !active) input.click();
      else if (input.checked === false && active) input.click();
    }
    if (active) elem.classList.add("active");
    else elem.classList.remove("active");
    if (toggle) {
      elem.addEventListener("click", () => {
        const inputEl = elem.querySelector("input");
        if (inputEl) {
          inputEl.click();
          if (inputEl.checked === true) {
            elem.classList.add("active");
          } else if (inputEl.checked === false) {
            elem.classList.remove("active");
          }
        } else {
          elem.classList.toggle("active");
        }
      });
    }
    const extraClicks = elem.getAttribute("data-click");
    if (extraClicks) {
      elem.addEventListener("click", () => {
        document.querySelectorAll(extraClicks).forEach((el) => el.click());
      });
    }
  });
}
async function setupToolButtons() {
  const appUiUx = state.appUiUx;
  const htmlPath2 = "/file=extensions-builtin/sdnext-modernui/html";
  const buttonMap = {
    apply: "paste",
    clear: "empty-set",
    close: "square-xmark",
    list: "list",
    load: "floppy-disk-circle-arrow-right",
    model: "database",
    override: "sliders",
    preview: "aperture",
    random: "shuffle",
    refresh: "arrows-rotate",
    remove: "eraser",
    reset: "empty-set",
    reuse: "recycle",
    save: "floppy-disk",
    scan: "radar",
    search: "magnifying-glass",
    select: "pen-swirl",
    size: "ruler-triangle",
    sort: "sort",
    swap: "arrow-up-arrow-down",
    upload: "upload",
    view: "grid"
  };
  const t0 = performance.now();
  if (!appUiUx) return;
  const processed = /* @__PURE__ */ new Set();
  for (const key of Object.keys(buttonMap)) {
    const iconName = buttonMap[key];
    const nodes = appUiUx.querySelectorAll(`.tool[id$="${key}"]`);
    nodes.forEach((el) => {
      if (processed.has(el)) return;
      processed.add(el);
      const wrapper = document.createElement("div");
      wrapper.className = "mask-icon";
      wrapper.style.maskImage = `url(${htmlPath2}/svg/${iconName}.svg)`;
      while (el.firstChild) wrapper.appendChild(el.firstChild);
      el.appendChild(wrapper);
    });
  }
  const t1 = performance.now();
  log("setupToolButtons", Math.round(t1 - t0));
  timer("setupToolButtons", t1 - t0);
}
async function setupDropdowns() {
  const appUiUx = state.appUiUx;
  if (!appUiUx) return;
  appUiUx.querySelectorAll(".gradio-dropdown").forEach((el) => {
    el.addEventListener("click", () => {
      const options = el.querySelector(".options");
      if (!options) return;
      const rect = options.getBoundingClientRect();
      if (el.id.startsWith("setting_")) {
        options.style.cssText = "top: 2.2em;";
      } else if (rect.bottom > window.innerHeight) {
        const offset = Math.min(500, rect.height);
        options.style.cssText = `top: -${offset}px !important;`;
      } else {
        options.style.cssText = "top: 2.2em;";
      }
    });
  });
}
async function createButtonsForExtensions() {
  const otherExtensions = document.querySelector("#other_extensions");
  const otherViews = document.querySelector("#split-left");
  const noButtonTabs = [
    "tab_txt2img",
    "tab_img2img",
    "tab_control",
    "tab_video",
    "tab_process",
    "tab_caption",
    "tab_gallery",
    "tab_models",
    "tab_extensions",
    "tab_system",
    "tab_info",
    "tab_sdnext_uiux_core"
  ];
  const snakeToCamel = (str) => str.replace(/(_\w)/g, (match) => match[1].toUpperCase());
  document.querySelectorAll("#tabs > .tabitem").forEach((c) => {
    const cid = c.id;
    const nid = cid.replace("tab_", "").replace("_tab", "");
    if (!noButtonTabs.includes(cid)) {
      const temp = document.createElement("div");
      let button;
      if (nid === "agent_scheduler") button = '<div class="mask-icon icon-calendar"></div>';
      if (nid === "framepack") button = '<div class="mask-icon icon-video"></div>';
      if (!button) button = `<div class="icon-letters">${nid.slice(0, 2)}</div>`;
      temp.innerHTML = `
        <button tabItemId="#split-app, #${cid}_tabitem"
          tabGroup="main_group" 
          data-click="#tabs" 
          class="xtabs-tab">${button}<span>${snakeToCamel(nid)}</span>
        </button>
      `;
      otherExtensions?.append(temp.firstElementChild);
      temp.innerHTML = `
        <div id="${cid}_tabitem" class="xtabs-item other">
          <div data-parent-selector="gradio-app" data-selector="#${cid} > div" class="portal"></div>
        </div>
      `;
      otherViews?.append(temp.firstElementChild);
    }
  });
}

// src/observers.ts
async function setupControlDynamicObservers() {
}
async function setupGenerateObservers() {
  function addButtonIcon(button, iconClass) {
    const icon = document.createElement("div");
    icon.classList.add("mask-icon", iconClass);
    button.appendChild(icon);
  }
  function addButtonSpan(button, spanText) {
    const span = document.createElement("span");
    span.textContent = spanText;
    if (!spanText) span.style.display = "none";
    button.appendChild(span);
  }
  function enableButtonAnimation(parentButton, enable) {
    if (!parentButton) return;
    if (enable) parentButton.classList.add("active");
    else parentButton.classList.remove("active");
  }
  const keys = ["#txt2img", "#img2img", "#extras", "#control", "#video"];
  keys.forEach((key) => {
    const loop = document.querySelector(`${key}_loop`);
    if (loop) loop.addEventListener("click", () => generateForever(`${key}_generate`));
    const tgb = document.querySelector(`${key}_generate`);
    if (tgb) {
      const tg = tgb.closest(".sd-button");
      new MutationObserver(() => {
        if (tgb.textContent && !tgb.querySelector("span")) {
          if (tgb.textContent === "Generate") {
            enableButtonAnimation(tg, false);
            addButtonIcon(tgb, "icon-generate");
          } else {
            enableButtonAnimation(tg, true);
          }
          addButtonSpan(tgb, tgb.textContent);
        }
      }).observe(tgb, { childList: true, subtree: true });
    }
    const teb = document.querySelector(`${key}_enqueue`);
    if (teb) {
      const te = teb.closest(".sd-button");
      new MutationObserver(() => {
        if (teb.textContent && !teb.querySelector("span")) {
          if (teb.textContent === "Enqueue") {
            enableButtonAnimation(te, false);
            addButtonIcon(teb, "icon-enqueue");
          } else {
            enableButtonAnimation(te, true);
          }
          addButtonSpan(teb, "");
        }
      }).observe(teb, { childList: true, subtree: true });
    }
    const tpb = document.querySelector(`${key}_pause`);
    if (tpb) {
      new MutationObserver(() => {
        if (tpb.textContent && !tpb.querySelector("span")) {
          if (tpb.textContent === "Pause") addButtonIcon(tpb, "icon-pause");
          else addButtonIcon(tpb, "icon-play");
          addButtonSpan(tpb, "");
        }
      }).observe(tpb, { childList: true, subtree: true });
    }
  });
  const captionBtn = document.querySelector("#btn_vlm_caption");
  if (captionBtn) {
    const captionButton = captionBtn.closest(".sd-button");
    new MutationObserver(() => {
      if (captionBtn.textContent && !captionBtn.querySelector("span")) {
        if (captionBtn.textContent === "Caption") {
          enableButtonAnimation(captionButton, false);
          addButtonIcon(captionBtn, "icon-caption");
        } else {
          enableButtonAnimation(captionButton, true);
        }
        addButtonSpan(captionBtn, captionBtn.textContent);
      }
    }).observe(captionBtn, { childList: true, subtree: true });
  }
}

// src/color-hue.ts
var hexToHSL = (hex) => {
  const rgb = /^#([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  if (!rgb) return { h: 0, s: 0, l: 0 };
  rgb.shift();
  const rgbNorm = rgb.map((c) => 1 * parseInt(c, 16) / 255);
  const max = Math.max(...rgbNorm);
  const min = Math.min(...rgbNorm);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case rgbNorm[0]:
        h = (rgbNorm[1] - rgbNorm[2]) / d + (rgbNorm[1] < rgbNorm[2] ? 6 : 0);
        break;
      case rgbNorm[1]:
        h = (rgbNorm[2] - rgbNorm[0]) / d + 2;
        break;
      case rgbNorm[2]:
        h = (rgbNorm[0] - rgbNorm[1]) / d + 4;
        break;
    }
    h /= 6;
  }
  return { h: Math.round(h * 360), s: Math.round(s * 100), l: Math.round(l * 100) };
};
var rgbtoHex = (r, g, b) => {
  const rh = r.toString(16).padStart(2, "0");
  const gh = g.toString(16).padStart(2, "0");
  const bh = b.toString(16).padStart(2, "0");
  return `#${rh}${gh}${bh}`;
};
var hslToRGB = (h, s, l) => {
  if (typeof h === "string" && h.includes("deg")) h = parseInt(h.replace("deg", ""));
  s /= 100;
  l /= 100;
  const k = (n) => (n + h / 30) % 12;
  const a = s * Math.min(l, 1 - l);
  const f = (n) => l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  return [Math.round(255 * f(0)), Math.round(255 * f(8)), Math.round(255 * f(4))];
};
async function setUserColors() {
  const t0 = performance.now();
  const h = localStorage.getItem("sd-primary-h");
  const s = localStorage.getItem("sd-primary-s");
  const l = localStorage.getItem("sd-primary-l");
  const el = document.getElementById("sd-primary-color");
  if (!el) return;
  el.value = rgbtoHex(...hslToRGB(h ?? "0", Number(s ?? 0), Number(l ?? 0)));
  if (h) document.documentElement.style.setProperty("--sd-primary-h", h);
  if (s) document.documentElement.style.setProperty("--sd-primary-s", s);
  if (l) document.documentElement.style.setProperty("--sd-primary-l", l);
  el.onchange = (evt) => {
    const hsl = hexToHSL(evt.target.value);
    log("setUserColors", hsl);
    document.documentElement.style.setProperty("--sd-primary-h", String(hsl.h));
    document.documentElement.style.setProperty("--sd-primary-s", String(hsl.s));
    document.documentElement.style.setProperty("--sd-primary-l", String(hsl.l));
    localStorage.setItem("sd-primary-h", String(hsl.h));
    localStorage.setItem("sd-primary-s", String(hsl.s));
    localStorage.setItem("sd-primary-l", String(hsl.l));
  };
  el.ondblclick = () => {
    localStorage.setItem("sd-primary-h", "180deg");
    localStorage.setItem("sd-primary-s", "60");
    localStorage.setItem("sd-primary-l", "40");
    setUserColors();
  };
  const t1 = performance.now();
  log("setUserColors", { h, s, l }, Math.round(t1 - t0));
  timer("setUserColors", t1 - t0);
}

// src/contributors.ts
async function getContributors(repoName, page = 1) {
  const request = await fetch(`https://api.github.com/repos/${repoName}/contributors?per_page=100&page=${page}`, {
    method: "GET",
    headers: { "Content-Type": "application/json" }
  });
  return request.json();
}
async function getAllContributors(repoName, page = 1, allContributors = []) {
  const list = await getContributors(repoName, page);
  const merged = allContributors.concat(list);
  if (list.length === 100) return getAllContributors(repoName, page + 1, merged);
  return merged;
}
async function getContributorsMultiple(repoNames) {
  const results = await Promise.all(repoNames.map((repoName) => getAllContributors(repoName)));
  const mergedMap = /* @__PURE__ */ new Map();
  for (const contributors of results) {
    for (const contributor of contributors) {
      const { login, contributions } = contributor;
      if (!mergedMap.has(login)) mergedMap.set(login, { ...contributor });
      else mergedMap.get(login).contributions += contributions;
    }
  }
  const mergedArray = Array.from(mergedMap.values());
  mergedArray.sort((a, b) => b.contributions - a.contributions);
  return mergedArray;
}
async function showContributors() {
  const contributorsBtn = document.querySelector("#contributors");
  const contributorsView = document.querySelector("#contributors_tabitem");
  if (!contributorsView) return;
  const temp = document.createElement("div");
  temp.id = "contributors_grid";
  temp.innerHTML = "<p>Retrieving contributor list<br>We are grateful for the many individuals who have generously put their time and effort to make this possible</p>";
  temp.style.display = "flex";
  temp.style.flexDirection = "column";
  temp.style.justifyContent = "center";
  temp.style.alignItems = "center";
  temp.style.height = "100%";
  temp.style.whiteSpace = "normal";
  contributorsView.append(temp);
  contributorsBtn?.addEventListener("click", async () => {
    if (!contributorsBtn.getAttribute("data-visited")) {
      contributorsBtn.setAttribute("data-visited", "true");
      const promise = getContributorsMultiple(["vladmandic/sdnext", "BinaryQuantumSoul/sdnext-ui-ux"]);
      promise.then((result) => {
        temp.innerHTML = "";
        temp.style.cssText = "";
        for (let i = 0; i < result.length; i++) {
          const login = result[i].login;
          const htmlUrl = result[i].html_url;
          const avatarUrl = result[i].avatar_url;
          temp.innerHTML += `
            <a href="${htmlUrl}" target="_blank" rel="noopener noreferrer nofollow" class="contributor-button flexbox col">
              <figure><img src="${avatarUrl}" lazy="true"></figure>
              <div class="contributor-name">${login}</div>
            </a>`;
        }
      });
    }
  });
}

// src/server-info.ts
var info = null;
var initial = true;
function toggleHide(name) {
  const el = document.getElementById(name);
  if (el) el.classList.toggle("hide");
}
window.toggleHide = toggleHide;
function jsonToHtml(heading, json, cls = "") {
  if (!json) return "";
  const entries = Object.entries(json);
  if (entries.length === 0) return "";
  return `
    <h3 onclick="toggleHide('server-info-table-${heading}')">${heading}</h3>
    <div class="server-info-table ${cls}" id="server-info-table-${heading}">
      <table class="table-wrap">
        ${entries.map(([key, value]) => `
            <tr>
              <td>${key}</td>
              <td>${typeof value === "object" ? JSON.stringify(value) : value}</td>
            </tr>
          `).join("")}
      </table>
    </div>
  `;
}
async function renderServerInfo() {
  if (!info) return;
  const el = document.getElementById("serverinfo");
  if (!el) return;
  el.innerHTML = `
    <div id="server-info-time">
      ${(/* @__PURE__ */ new Date()).toLocaleString()}
    </div>
    ${jsonToHtml("Version", info.version)}
    ${jsonToHtml("Model", info.model)}
    ${jsonToHtml("Torch", info.torch)}
    ${jsonToHtml("GPU", info.gpu)}
    ${jsonToHtml("Platform", info.platform)}
    ${jsonToHtml("Status", info.status, "hide")}
    ${jsonToHtml("Memory", info.memory, "hide")}
    ${jsonToHtml("Browser", info.browser, "hide")}
  `;
}
async function getServerInfo() {
  const versionReq = await authFetch(`${window.api}/version`);
  const torchReq = await authFetch(`${window.api}/torch`);
  const gpuReq = await authFetch(`${window.api}/gpu`);
  const statusReq = await authFetch(`${window.api}/status`);
  const memoryReq = await authFetch(`${window.api}/memory`);
  const platformReq = await authFetch(`${window.api}/platform`);
  const modelReq = await authFetch(`${window.api}/checkpoint`);
  info = {
    version: versionReq.ok ? await versionReq.json() : {},
    model: modelReq.ok ? await modelReq.json() : {},
    torch: torchReq.ok ? await torchReq.json() : {},
    gpu: gpuReq.ok ? await gpuReq.json() : {},
    status: statusReq.ok ? await statusReq.json() : {},
    memory: memoryReq.ok ? await memoryReq.json() : {},
    platform: platformReq.ok ? await platformReq.json() : {},
    browser: { agent: navigator.userAgent }
  };
  if (initial) log("getServerInfo", info);
  renderServerInfo();
}
async function initServerInfo() {
  let refreshTimer = null;
  const el = document.getElementById("serverinfo");
  if (!el) return;
  const observer = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        if (initial) getServerInfo();
        if (!refreshTimer) refreshTimer = setInterval(getServerInfo, 1e4);
        initial = false;
      } else {
        if (refreshTimer) clearInterval(refreshTimer);
        refreshTimer = null;
      }
    });
  });
  observer.observe(el);
  const btnCopy = document.getElementById("serverinfo-copy");
  if (!btnCopy) return;
  btnCopy.addEventListener("click", (evt) => {
    evt.preventDefault();
    evt.stopPropagation();
    if (!info) return;
    const infoToCopy = {
      version: info.version,
      model: info.model,
      torch: info.torch,
      gpu: info.gpu,
      platform: info.platform
    };
    navigator.clipboard.writeText(JSON.stringify(infoToCopy, null, 2));
    log("infoCopy", infoToCopy);
  });
}

// src/logger.ts
function logPrettyPrint(...args) {
  let output = "";
  const dt = /* @__PURE__ */ new Date();
  const [h, m, s, ms] = [dt.getHours().toString(), dt.getMinutes().toString(), dt.getSeconds().toString(), dt.getMilliseconds().toString()];
  const ts = `${h.padStart(2, "0")}:${m.padStart(2, "0")}:${s.padStart(2, "0")}.${ms.padStart(3, "0")}`;
  output += `<div class="log-row"><span class="log-date">${ts}</span>`;
  for (let i = 0; i < args.length; i++) {
    let arg = args[i];
    if (arg === void 0) arg = "undefined";
    if (arg === null) arg = "null";
    const argstr = String(arg).toLowerCase();
    let acolor = "";
    if (argstr.indexOf("error") !== -1) {
      acolor += " log-remove";
    } else if (argstr.indexOf("loading") !== -1 || argstr.indexOf("load") !== -1 || argstr.indexOf("init") !== -1 || argstr.indexOf("submit") !== -1 || argstr.indexOf("success") !== -1) {
      acolor += " log-load";
    } else if (argstr.indexOf("[") !== -1) {
      acolor += " log-object";
    }
    if (String(arg).indexOf(".css") !== -1 || String(arg).indexOf(".html") !== -1) acolor += " log-url";
    else if (String(arg).indexOf("\n") !== -1) output += "<br />";
    output += `<span class="log-${typeof arg} ${acolor}">`;
    if (typeof arg === "object") output += JSON.stringify(arg);
    else output += arg;
    output += " </span>";
  }
  output += "</div>";
  return output;
}
async function setupLogger() {
  const uiDisabled = Array.isArray(window.opts.ui_disabled) ? window.opts.ui_disabled : [];
  if (uiDisabled?.includes("logs")) return;
  const logMonitorJS = document.createElement("div");
  logMonitorJS.id = "logMonitorJS";
  document.body.append(logMonitorJS);
  window.logger = logMonitorJS;
  window.logPrettyPrint = logPrettyPrint;
}
function largeErrorOverlay(msg, err) {
  const overlay = document.createElement("div");
  overlay.style.cssText = "position:fixed;top:0;left:0;width:100%;height:100%;background-color:rgba(255, 0, 0, 0.2);display:flex;align-items:center;justify-content:center;pointer-events:none;z-index:9999;";
  const content = document.createElement("div");
  content.style.cssText = "background-color:#fff;color:#000;padding:10px;max-width:90%;display:flex;flex-direction:column;gap:10px;pointer-events:auto";
  const header = document.createElement("div");
  header.style.cssText = "font-size:1.5em;font-weight:bold;margin-bottom:10px;text-align:center;";
  header.textContent = msg;
  const summary = document.createElement("div");
  summary.textContent = String(err);
  const stack = document.createElement("pre");
  stack.style.cssText = "white-space:pre-wrap;word-break:break-word;max-height:70vh;overflow-y:auto;";
  stack.textContent = err.stack || new Error().stack || "";
  const dismiss = document.createElement("button");
  dismiss.textContent = "Close";
  dismiss.style.cssText = "margin-top:10px;align-self:center;padding:5px 10px;background-color:var(--color-error);";
  dismiss.onclick = () => overlay.remove();
  content.append(header, summary, stack, dismiss);
  overlay.appendChild(content);
  document.body.appendChild(overlay);
}

// src/templates.ts
async function replaceRootTemplate(appId) {
  state.appUiUx = document.querySelector(appId);
  if (!state.appUiUx) {
    throw new Error(`Root element with id "${appId}" not found`);
  }
  gradioApp().insertAdjacentElement("afterbegin", state.appUiUx);
}
async function getNestedTemplates(container) {
  const nestedData = [];
  container.querySelectorAll(".template").forEach((el) => {
    nestedData.push({
      template: el.getAttribute("template") ?? "",
      key: el.getAttribute("key"),
      target: el
    });
  });
  return nestedData;
}
async function loadCurrentTemplate(data, htmlPath2) {
  const currData = data.shift();
  if (currData) {
    const t0 = performance.now();
    const uiDisabled = Array.isArray(window.opts.ui_disabled) ? window.opts.ui_disabled : [];
    for (const disabled of uiDisabled) {
      if (currData.template.includes(disabled)) {
        log("loadTemplate", currData.template, "disabled");
        return loadCurrentTemplate(data, htmlPath2);
      }
    }
    const uri = `${window.subpath}${htmlPath2}/templates/${currData.template}.html?${Date.now()}`;
    const response = await fetch(uri, { cache: "reload" });
    if (!response.ok) {
      error("loadTemplate", currData.template, currData.target);
      if (currData.target) currData.target.setAttribute("status", "error");
    } else {
      const text = await response.text();
      const tempDiv = document.createElement("div");
      tempDiv.innerHTML = currData.key ? text.replace(/\s*\{\{.*?\}\}\s*/g, currData.key) : text;
      const nestedData = await getNestedTemplates(tempDiv);
      data.push(...nestedData);
      if (currData.target) {
        currData.target.setAttribute("status", "true");
        currData.target.append(tempDiv.firstElementChild);
      } else {
        error("loadTemplateNoTarget", currData);
      }
    }
    const t1 = performance.now();
    timer(`loadTemplate:${currData.template}`, t1 - t0);
    return loadCurrentTemplate(data, htmlPath2);
  }
  return Promise.resolve();
}
async function loadAllTemplates(htmlPath2, rootTemplate2, tabId2) {
  const data = [
    {
      template: rootTemplate2,
      key: null,
      target: document.querySelector(tabId2)
    }
  ];
  if (!data[0].target) error("LoadAllTemplates: missing target", data);
  const t0 = performance.now();
  await loadCurrentTemplate(data, htmlPath2);
  const t1 = performance.now();
  timer("loadAllTemplates:load", t1 - t0);
  await replaceRootTemplate("#sdnext_app");
  const t2 = performance.now();
  timer("loadAllTemplates:replace", t2 - t1);
  log("loadAllTemplates", `load=${Math.round(t1 - t0)} replace=${Math.round(t2 - t1)}`);
}

// src/portals.ts
var failedPortals = [];
function rememberFailedPortal(portalElem) {
  if (!failedPortals.includes(portalElem)) {
    failedPortals.push(portalElem);
  }
}
function movePortal(portalElem, tries, index, length) {
  const MAX_TRIES = 3;
  const parentSelector = portalElem.getAttribute("data-parent-selector");
  const dataSelector = portalElem.getAttribute("data-selector");
  const dataOptional = portalElem.getAttribute("data-optional");
  const targetElem = document.querySelector(`${parentSelector} ${dataSelector}`);
  if (portalElem && !targetElem && dataSelector?.endsWith("_enqueue")) {
    state.portalTotal += 1;
    portalElem.style.display = "none";
  } else if (portalElem && targetElem) {
    portalElem.append(targetElem);
    state.portalTotal += 1;
    const droppable = portalElem.getAttribute("droppable");
    if (droppable) {
      Array.from(portalElem.children).forEach((child) => {
        if (child !== targetElem) {
          if (targetElem.className.indexOf("gradio-accordion") !== -1) targetElem.children[2].append(child);
          else targetElem.append(child);
        }
      });
    }
    const showButton = portalElem.getAttribute("show-button");
    if (showButton) document.querySelector(showButton)?.classList.remove("hidden");
  } else if (dataOptional === "true") {
    state.portalTotal += 1;
    rememberFailedPortal(portalElem);
  } else if (tries < MAX_TRIES) {
    log("retryPortal", portalElem, tries);
    const timeout = portalElem.getAttribute("data-timeout");
    const delay = timeout ? parseInt(timeout) : 500;
    setTimeout(() => movePortal(portalElem, tries + 1, index, length), delay);
  } else {
    error("Element not found", { index, parent: parentSelector, id: dataSelector, el: portalElem, tgt: targetElem });
    portalElem.style.backgroundColor = "var(--color-error)";
    state.portalTotal += 1;
    rememberFailedPortal(portalElem);
  }
  if (state.portalTotal === length) state.uiFlagPortalInitialized = true;
}
async function loadAllPortals() {
  if (!state.appUiUx) {
    error("loadAllPortals: appUiUx not found");
    return;
  }
  const t0 = performance.now();
  const portals = state.appUiUx.querySelectorAll(".portal");
  portals.forEach((elem, index, array) => movePortal(elem, 1, index, array.length));
  const t1 = performance.now();
  log("loadAllPortals", `time=${Math.round(t1 - t0)} portals=${portals.length}`);
  timer("loadAllPortals", t1 - t0);
}
function loadRetryPortals() {
  log("loadRetryPortals", { portals: failedPortals.length });
  if (failedPortals.length === 0) return;
  const pending = failedPortals.splice(0, failedPortals.length);
  pending.forEach((portalElem) => {
    const parentSelector = portalElem.getAttribute("data-parent-selector");
    const dataSelector = portalElem.getAttribute("data-selector");
    const targetElem = document.querySelector(`${parentSelector} ${dataSelector}`);
    if (portalElem && targetElem) {
      portalElem.append(targetElem);
      const droppable = portalElem.getAttribute("droppable");
      if (droppable) {
        Array.from(portalElem.children).forEach((child) => {
          if (child !== targetElem) {
            if (targetElem.className.indexOf("gradio-accordion") !== -1) targetElem.children[2].append(child);
            else portalElem.append(child);
          }
        });
      }
      const showButton = portalElem.getAttribute("show-button");
      if (showButton) document.querySelector(showButton)?.classList.remove("hidden");
    } else {
      rememberFailedPortal(portalElem);
    }
  });
}

// src/styles.ts
async function removeStyleAssets() {
  const t0 = performance.now();
  let removedStylesheets = 0;
  document.querySelectorAll(`
    [rel="stylesheet"][href*="/assets/"], 
    [rel="stylesheet"][href*="theme.css"],
    [rel="stylesheet"][href*="base.css"],
    [rel="stylesheet"][href*="file=style.css"]
  `).forEach((stylesheet) => {
    stylesheet.remove();
    removedStylesheets++;
    if (window.opts.uiux_enable_console_log) log("removeStylesheet", stylesheet.getAttribute("href"));
  });
  const stylers = document.querySelectorAll('.styler, [class*="svelte"]:not(input)');
  let count = 0;
  let removedCount = 0;
  stylers.forEach((element) => {
    const htmlElem = element;
    if (htmlElem.style.display !== "none" && htmlElem.style.display !== "block") {
      htmlElem.removeAttribute("style");
      removedCount++;
    }
    [...element.classList].filter((className) => className.match(/^svelte.*/)).forEach((svelteClass) => element.classList.remove(svelteClass));
    count++;
  });
  const t1 = performance.now();
  log("removeElements", `elements=${removedCount}/${count} stylesheets=${removedStylesheets} time=${Math.round(t1 - t0)}`);
  timer("removeElements", t1 - t0);
}

// src/options.ts
async function uiuxOptionSettings() {
  let el;
  function showInputRangeTicks() {
    gradioApp().querySelectorAll("input[type='range']").forEach((elem) => {
      const rangeElem = elem;
      const spacing = Number(rangeElem.step) / (Number(rangeElem.max) - Number(rangeElem.min)) * 100;
      const tsp = `max(3px, calc(${spacing}% - 1px))`;
      const fsp = `max(4px, calc(${spacing}% + 0px))`;
      const overlay = `repeating-linear-gradient(90deg, transparent, transparent ${tsp}, var(--sd-input-border-color) ${tsp}, var(--sd-input-border-color) ${fsp})`;
      rangeElem.style.setProperty("--sd-slider-bg-overlay", overlay);
    });
  }
  showInputRangeTicks();
  function setupUiUxSetting(settingId, className) {
    const appUiUx = state.appUiUx;
    function updateUiUxClass(cn, value) {
      if (!appUiUx) return;
      if (value) appUiUx.classList.add(cn);
      else appUiUx.classList.remove(cn);
    }
    el = gradioApp().querySelector(`#setting_${settingId} input`);
    if (el) el.addEventListener("click", (e) => updateUiUxClass(className, e.target.checked));
    updateUiUxClass(className, window.opts[settingId]);
  }
  setupUiUxSetting("uiux_hide_legacy", "option-hide-legacy");
  setupUiUxSetting("uiux_no_slider_layout", "option-no-slider-layout");
  setupUiUxSetting("uiux_show_labels_aside", "option-aside-labels");
  setupUiUxSetting("uiux_show_labels_main", "option-main-labels");
  setupUiUxSetting("uiux_show_labels_tabs", "option-tab-labels");
  setupUiUxSetting("uiux_show_labels_tabs", "option-txt2img-labels");
  setupUiUxSetting("uiux_show_labels_tabs", "option-img2img-labels");
  setupUiUxSetting("uiux_show_labels_tabs", "option-control-labels");
  setupUiUxSetting("uiux_show_labels_tabs", "option-video-labels");
  setupUiUxSetting("uiux_no_headers_params", "option-hide-headers-params");
  setupUiUxSetting("uiux_show_outline_params", "option-show-outline-params");
  log("hideLegacy", window.opts.uiux_hide_legacy);
  function mobileScale(value) {
    const viewport = document.head.querySelector('meta[name="viewport"]');
    if (viewport) viewport.setAttribute("content", `width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=${value}`);
  }
  el = gradioApp().querySelector("#setting_uiux_mobile_scale input[type=number]");
  if (el) el.addEventListener("change", (e) => mobileScale(e.target.value));
  mobileScale(window.opts.uiux_mobile_scale);
  const panelMinWidth = (value) => document.documentElement.style.setProperty("--sd-panel-min-width", `${value}em`);
  el = gradioApp().querySelector("#setting_uiux_panel_min_width input[type=number]");
  if (el) el.addEventListener("change", (e) => panelMinWidth(e.target.value));
  panelMinWidth(window.opts.uiux_panel_min_width);
  const gridImageSize = (value) => document.documentElement.style.setProperty("--sd-grid-image-size", `${value}px`);
  el = gradioApp().querySelector("#setting_uiux_grid_image_size input[type=number]");
  if (el) el.addEventListener("change", (e) => gridImageSize(e.target.value));
  gridImageSize(window.opts.uiux_grid_image_size);
}

// src/layout.ts
var isMobile = () => window.innerWidth < window.innerHeight;
function trackAsideFocus() {
  if (!state.appUiUx) return;
  const aside = state.appUiUx.querySelector("#aside-panel");
  if (!aside) return;
  aside.addEventListener("focusin", () => {
    state.asideFocusTracker += 1;
  });
  aside.addEventListener("focusout", () => {
    setTimeout(() => {
      state.asideFocusTracker -= 1;
    }, 200);
  });
}
function applyDefaultLayout(mobile) {
  if (!state.appUiUx) return;
  const appUiUx = state.appUiUx;
  appUiUx.querySelectorAll("[mobile]").forEach((tabItem) => {
    if (mobile) {
      if (tabItem.childElementCount === 0) {
        const mobileTarget = appUiUx.querySelector(tabItem.getAttribute("mobile") ?? "");
        if (mobileTarget) {
          const targetParentId = mobileTarget.parentElement?.id;
          if (targetParentId) tabItem.setAttribute("mobile-restore", `#${targetParentId}`);
          tabItem.append(mobileTarget);
        }
      }
    } else if (tabItem.childElementCount > 0) {
      const mobileRestoreTarget = appUiUx.querySelector(tabItem.getAttribute("mobile-restore") ?? "");
      if (mobileRestoreTarget) {
        tabItem.removeAttribute("mobile-restore");
        mobileRestoreTarget.append(tabItem.firstElementChild);
      }
    }
  });
  if (mobile) {
    appUiUx.querySelector(".accordion-vertical.expand #mask-icon-acc-arrow")?.dispatchEvent(new MouseEvent("click"));
    const accArrow = appUiUx.querySelector(".accordion-vertical.expand #mask-icon-acc-arrow");
    accArrow?.click();
    if (!appUiUx.querySelector(".accordion-vertical.expand #mask-icon-acc-arrow-control")) {
      appUiUx.querySelector(".accordion-vertical #mask-icon-acc-arrow-control")?.click();
    }
    if (state.asideFocusTracker === 0) {
      if (appUiUx.querySelector("#accordion-aside")?.classList.contains("expand")) {
        appUiUx.querySelector("#acc-arrow-button")?.click();
      }
    }
    appUiUx.classList.add("media-mobile");
    appUiUx.classList.remove("media-desktop");
  } else {
    appUiUx.classList.add("media-desktop");
    appUiUx.classList.remove("media-mobile");
  }
}
function switchMobile() {
  const optslayout = window.opts.uiux_default_layout;
  if (optslayout === "Auto") {
    window.addEventListener("resize", () => applyDefaultLayout(isMobile()));
    applyDefaultLayout(isMobile());
  } else if (optslayout === "Mobile") {
    applyDefaultLayout(true);
  } else if (optslayout === "Desktop") {
    applyDefaultLayout(false);
  }
}
async function applyAutoHide() {
  if (!state.appUiUx) return;
  const hideSiblings = (elem) => {
    if (!elem || elem.nodeName !== "DIV") return;
    elem.classList.toggle("hidden-animate");
    hideSiblings(elem.nextElementSibling);
  };
  state.appUiUx.querySelectorAll("h2").forEach((elem) => elem.classList.add("auto-hide"));
  state.appUiUx.querySelectorAll(".auto-hide").forEach((elem) => {
    const id = elem.id || elem.innerText;
    elem.onclick = (evt) => {
      elem.classList.toggle("minimize");
      setStored(`hide_${id}`, elem.classList.contains("minimize"));
      for (const child of evt.target.children) child.classList.toggle("hidden-animate");
      hideSiblings(evt.target?.nextElementSibling);
      log("autoHide", { id, hide: elem.classList.contains("minimize") });
    };
    if (getStored(`hide_${id}`)) {
      elem.click();
    }
  });
  const minimizeToggle = (el, evt) => {
    if (evt.target === el || evt.target === el.firstElementChild || evt.target.parentElement === el.firstElementChild || el.firstElementChild?.contains(evt.target) && evt.target.nodeName === "H2") {
      const id = el.id || el.innerText;
      el.classList.toggle("minimize");
      setStored(`hide_${id}`, el.classList.contains("minimize"));
      log("autoHide", { id, hide: el.classList.contains("minimize") });
      evt.stopPropagation();
      evt.stopImmediatePropagation();
    }
  };
  const panels = [
    document.querySelector("#control-template-column-input"),
    document.querySelector("#control-template-column-output"),
    document.querySelector("#img2img-template-column-input"),
    document.querySelector("#img2img-template-column-output")
  ];
  panels.forEach((panel) => {
    if (panel) {
      const id = panel.id || panel.innerText;
      panel.addEventListener("click", (evt) => minimizeToggle(panel, evt));
      if (getStored(`hide_${id}`)) panel.click();
    }
  });
}
function setupAnimationEventListeners() {
  document.addEventListener("animationstart", (e) => {
    if (e.animationName === "fade-in") {
      e.target.classList.remove("hidden");
    }
  });
  document.addEventListener("animationend", (e) => {
    if (e.animationName === "fade-out") {
      e.target.classList.add("hidden");
    }
  });
}
async function extraTweaks() {
  const t0 = performance.now();
  document.querySelectorAll("#system .tab-nav button")[1]?.click();
  const controlColumns = document.getElementById("control-columns");
  if (!controlColumns) return;
  const controlColumnsElement = controlColumns;
  const anyControlColumns = controlColumnsElement;
  async function adjustFlexDirection(evt) {
    const w = Math.floor((evt[0]?.contentRect.width ?? 0) / 8);
    if (w === anyControlColumns.prevWidth) return;
    anyControlColumns.prevWidth = w;
    const firstElementChild = controlColumnsElement.firstElementChild;
    if (!firstElementChild) return;
    const childCount = controlColumnsElement.childElementCount;
    const firstChildMinWidth = parseFloat(getComputedStyle(firstElementChild).minWidth);
    const gapWidth = parseFloat(getComputedStyle(controlColumnsElement).gap);
    const minWidth = childCount * firstChildMinWidth + (childCount - 1) * gapWidth;
    const currentWidth = controlColumnsElement.clientWidth;
    if (currentWidth < minWidth && !controlColumnsElement.classList.contains("flex-force-column")) {
      controlColumnsElement.classList.add("flex-force-column");
      controlColumnsElement.classList.remove("flex-force-row");
    } else if (currentWidth >= minWidth && controlColumnsElement.classList.contains("flex-force-column")) {
      controlColumnsElement.classList.remove("flex-force-column");
      controlColumnsElement.classList.add("flex-force-row");
    }
  }
  async function toggleControlOrientation(forceRow = false, disconnectObserver = false) {
    if (forceRow) {
      document.documentElement.style.setProperty("--sd-panel-min-width", "512px");
      controlColumnsElement.classList.add("flex-force-column");
      controlColumnsElement.classList.remove("flex-force-row");
    } else if (controlColumnsElement.classList.contains("flex-force-column")) {
      document.documentElement.style.setProperty("--sd-panel-min-width", "128px");
      controlColumnsElement.classList.remove("flex-force-column");
      controlColumnsElement.classList.add("flex-force-row");
    } else {
      document.documentElement.style.setProperty("--sd-panel-min-width", "512px");
      controlColumnsElement.classList.add("flex-force-column");
      controlColumnsElement.classList.remove("flex-force-row");
    }
    if (disconnectObserver && anyControlColumns.resizeObserver) {
      anyControlColumns.resizeObserver.disconnect();
      delete anyControlColumns.resizeObserver;
    }
  }
  anyControlColumns.resizeObserver = new ResizeObserver(adjustFlexDirection);
  anyControlColumns.resizeObserver.observe(controlColumnsElement);
  const controlOrientationBtn = document.getElementById("control_panel_orientation");
  controlOrientationBtn?.addEventListener("click", () => toggleControlOrientation(false, true));
  setTimeout(() => {
    const panelInput = document.getElementById("control-template-column-input");
    const panelOutput = document.getElementById("control-template-column-output");
    const forceRow = panelInput?.classList.contains("minimize") || panelOutput?.classList.contains("minimize");
    toggleControlOrientation(forceRow, false);
  }, 10);
  ["txt2img", "img2img", "control", "video"].forEach((key) => {
    const buttonNav = document.getElementById(`${key}_nav`);
    const buttonEN = document.getElementById(`btn-en-layout-${key}`);
    buttonNav?.addEventListener("click", () => buttonEN?.click());
  });
  const logoNav = document.getElementById("logo_nav");
  const txt2imgNav = document.getElementById("txt2img_nav");
  const img2imgNav = document.getElementById("img2img_nav");
  const controlNav = document.getElementById("control_nav");
  const videoNav = document.getElementById("video_nav");
  logoNav?.addEventListener("click", () => controlNav?.click());
  const buttonCurrent = document.getElementById(getStored("tab-main_group-current") ?? "") || logoNav;
  buttonCurrent?.click();
  const handleTabChange = (evt) => {
    const tabname = evt.target.id.split("_")[0];
    for (const tab of ["txt2img", "img2img", "control", "video"]) {
      const el = document.getElementById(`tab_${tab}`);
      if (el) el.style.display = tabname === tab ? "block" : "none";
    }
  };
  txt2imgNav?.addEventListener("click", handleTabChange);
  img2imgNav?.addEventListener("click", handleTabChange);
  controlNav?.addEventListener("click", handleTabChange);
  videoNav?.addEventListener("click", handleTabChange);
  const serverLog = document.getElementById("logMonitorData");
  const btnWrap = document.getElementById("btn_console_log_server_wrap");
  if (btnWrap) {
    btnWrap.onclick = () => {
      if (serverLog) serverLog.style.whiteSpace = serverLog.style.whiteSpace === "nowrap" ? "break-spaces" : "nowrap";
    };
  }
  const clientLog = document.getElementById("logMonitorJS");
  const btnClientWrap = document.getElementById("btn_console_log_client_wrap");
  if (btnClientWrap) {
    btnClientWrap.onclick = () => {
      if (clientLog) clientLog.classList.toggle("wrap-div");
    };
  }
  const uiDisabled = Array.isArray(window.opts.ui_disabled) ? window.opts.ui_disabled : [];
  if (uiDisabled?.includes("logs")) {
    if (serverLog) serverLog.style.display = "none";
    if (clientLog) clientLog.style.display = "none";
  }
  document.querySelectorAll('input[type="text"], textarea').forEach((elem) => {
    elem.setAttribute("spellcheck", "false");
  });
  const t1 = performance.now();
  log("extraTweaks", Math.round(t1 - t0));
  timer("extraTweaks", t1 - t0);
}

// src/index.ts
var htmlPath = "/file=extensions-builtin/sdnext-modernui/html";
var rootTemplate = "template-app-root";
var tabId = "#tab_sdnext_uiux_core";
window.getUICurrentTabContent = () => gradioApp().querySelector(".xtabs-item:not(.hidden) > .split");
window.getSettingsTabs = () => gradioApp().querySelectorAll("#layout-settings .tabitem");
window.waitForUiReady = functionWaitForFlag(() => state.uiFlagInitialized);
var waitForUiPortal = functionWaitForFlag(() => state.uiFlagPortalInitialized);
async function mainUiUx() {
  try {
    const t0 = performance.now();
    log("initModernUi");
    log("userAgent", navigator?.userAgent);
    await removeStyleAssets();
    await setupLogger();
    await loadAllTemplates(htmlPath, rootTemplate, tabId);
    createButtonsForExtensions();
    setupAnimationEventListeners();
    initSplitComponents();
    await loadAllPortals();
    initTabComponents();
    initButtonComponents();
    setupToolButtons();
    setupDropdowns();
    initAccordionComponents();
    const t1 = performance.now();
    await waitForUiPortal();
    const t2 = performance.now();
    log("waitForUiPortal", Math.round(t2 - t1));
    setupGenerateObservers();
    setupControlDynamicObservers();
    uiuxOptionSettings();
    setUserColors();
    showContributors();
    switchMobile();
    restoreAccordionState();
    trackAsideFocus();
    applyAutoHide();
    extraTweaks();
    initServerInfo();
    loadRetryPortals();
    state.uiFlagInitialized = true;
    const t3 = performance.now();
    log("mainUiUx", { total: Math.round(t3 - t0), load: Math.round(t1 - t0), portal: Math.round(t2 - t1), post: Math.round(t3 - t2) });
    timer("waitForUiPortal:total", t3 - t0);
    timer("waitForUiPortal:load", t1 - t0);
    timer("waitForUiPortal:portal", t2 - t1);
    timer("waitForUiPortal:post", t3 - t2);
  } catch (err) {
    const msg = "An error occurred during ModernUI initialization";
    try {
      error(msg, err);
    } catch {
      console.error(msg, err);
    }
    largeErrorOverlay(msg, err);
  }
}
onUiReady(mainUiUx);
//# sourceMappingURL=modernui.mjs.map
