name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: Describe the feature in a clear and simple way
      value: 
  - type: textarea
    id: platform
    attributes:
      label: Version Platform Description
      description: Describe your platform (program version, OS, browser)
      value: 
  - type: markdown
    attributes:
      value: |
        If unsure if this is a right place to ask your question, perhaps post on [Discussions](https://github.com/vladmandic/automatic/discussions)
        Or reach-out to us on [Discord](https://discord.gg/WqMzTUDC)
